baseURL: https://zishu.me/
languageCode: en-us
title: 子舒的博客
theme: 10 # 10
pagination:
  pagerSize: 9 # 首页文章显示个数
summaryLength: 999999 # 首页文章摘要字数
hasCJKLanguage: true
rssLimit: 10 # 限制 rss 输出的数量

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2 # 从 h2 开始
    endLevel: 3 # 到 h4 结束
    ordered: false # 生成 ul 而不是 ol

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  blog: /blog/:slug.html/ # 文章输出 url 格式

params:
  title: 子舒的博客
  description: 一个热爱生活的前端开发工程师。
  logo:  https://imgurl.zishu.me/author.png # 博主头像
  author:
    name: "子舒"
    email: "anghunk@gmail.com"
  favicon:  https://imgurl.zishu.me/favicon.ico # 网站 favicon 图标
  buildDate: 2020-06-14 # 建站日期
  
  socials: # 导航
    - name: 首页
      link: /
    - name: 文章
      link: /blog/
    - name: 标签
      link: /tags/
    - name: 留言
      link: /message/
    - name: 关于
      link: /about/
    - name: 项目
      link: /projects/
    - name: 友链
      link: /friends/


sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5